#!/usr/bin/python

import time

#Wait while everything is prepared
time.sleep(60)

import pypresence

import psutil

client_id = "1011262187739815998"

RPC = pypresence.Presence(client_id)

connected = False

while connected == False:

    try:
        RPC.connect()
        RPC.update(
                state= "wm - bspwm",
                details= "host - framework laptop",
                large_image = "arch_logo",
                start = psutil.boot_time()
                )
        connected = True

    except:
        time.sleep(30) 

while True:
    time.sleep(60)
